apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paulatwo-chart.fullname" . }}
  labels:
    {{- include "paulatwo-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "paulatwo-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "paulatwo-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}"
        ports:
         - containerPort: {{ .Values.service.port }}